### ISSUE TITLE
There is no deleting image function after deployment

### ISSUE THREAD

**Issue by ghost** [kwk/docker-registry-frontend#150] opened 2016-08-11 02:02 UTC
## Expected behavior
- [x] On the /repositories/ web page, can select repositories to perform deleting operation.
## Actual behavior
- [x] On the /repositories/ web page, only can view the repositories, there is no deleting operation can be done.  

![web-repository](https://lh3.googleusercontent.com/3tislW-GVu4ZjOHn010XzkUVAH7G-rhUn2Wy91h3bC6i4eQYNm8qROtt6LIcT4vEpllA7pfXZGqLsJk7Hv6LZgHAxfjzaoqFCKD4KiF4thxS4gJH8VioPi4yooQXL0SH6WZz3jtAVycBFxzPGNVk0eNlafPNpGOnxFQ-DssIEPoF_PWYx1QoesNJCvkLQgmKdikWaM7laBVJiFLRzJvCZolvbR3Sa11yGpwNaa4hkeNfz_U2ORvah06PWlCEls7fc6zX5oqSfrOoITQvlCjx-Z-as7tMHZ0tDCXBBNtbgdkZKJhi_dg7C-VjzBTGsRyU88agy64vps21oOrSDt69OFgRTaKP8zFACK9GQmcoZ0w_rUSVBwq-45pgoFCE4Ew6_skO1H1nZAIktdsehyOkh88FDqatHWYByoexk_5pzo6bRLfYCzlqfDCx4SFX7aO_Ca2ZJnN2zNLPJrmtYW50Cv_v9AAr3sIpyiOOknLbYsaeujsUpScQnD6OwlkYLC_PsuhT8Q50TcnvglkEFLkXk0GIwtSq0ldhTpvquSwo5S24K8iSkRYT0NifcT5dFR1ILOK_Vkqc2JW8lJXzX3rDbjMFZqxVosvX=w1196-h371-no)
## Steps to reproduce the problem
- [x] Deployed with docker, below are the configuration:  

Environments for registry:  
- SEARCH_BACKEND=sqlalchemy  
- SQLALCHEMY_INDEX_DATABASE=sqlite:////tmp/docker-registry.db  
- REGISTRY_STORAGE_DELETE_ENABLED=true  

Environments for registry-frontend:  
- ENV_DOCKER_REGISTRY_HOST=http://registry.srv
- ENV_DOCKER_REGISTRY_PORT=5000
- ENV_REGISTRY_PROXY_FQDN=registry.example.net
- ENV_REGISTRY_PROXY_PORT=443

Nginx config:  

```
  location /v2/ {
    # Do not allow connections from docker 1.5 and earlier
    # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
    if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
      return 404;
    }

    # To add basic authentication to v2 use auth_basic setting plus add_header
    auth_basic "registry.localhost";
    auth_basic_user_file /etc/nginx/conf.d/registry.password;
    add_header 'Docker-Distribution-Api-Version' 'registry/2.0' always;

    proxy_pass                          http://docker-registry;
    proxy_set_header  Host              $http_host;   # required for docker client's sake
    proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
    proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto $scheme;
    proxy_read_timeout                  900;
  }

  location / {
    # basic authentication
    auth_basic "registry-frontend.web";
    auth_basic_user_file /etc/nginx/conf.d/registry.password;

    proxy_pass                          http://registry-frontend;
    proxy_set_header  Host              $http_host;
    proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
#    proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
#    proxy_set_header  X-Forwarded-Proto $scheme;
    proxy_read_timeout              900;
  }
```
## Specifications
- [x] Which version of docker (`docker version`) are you running?  

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```
- [x] Which operating system do you use?
  `ubuntu-14.04`  
- [x] Which version of the docker-registry-frontend are you running?
  `v2`
  `This is git revision: 3ad864b`

**Comment by kwk** [comment] 2016-08-11 05:11
Thank you for your report. Currently browse only mode is enforced: https://github.com/kwk/docker-registry-frontend/blob/v2/README.md#browse-mode

Duplicate of  #106

**Closed as completed by kwk** 2016-08-11 05:11 UTC
