### ISSUE TITLE
Does not pickup v1 registry after last couple of commits

### ISSUE THREAD

**Issue by krunchyal** [kwk/docker-registry-frontend#57] opened 2015-07-08 14:07 UTC
Have a version of this container revision ff69f40 which works perfectly.
Same machine with a newer revision df65ffb unfortunately does not pickup any of the containers in my registry.

The page never seems to completely finish loading properly either. The loading bar along the top of the page (Chrome) just hangs at 90%.

**Comment by moimael** [comment] 2015-07-22 10:05
Yep same for me, it do not pick the port and the use_ssl env var.

**Comment by rubytastic** [comment] 2015-07-22 15:26
So its not usable at the moment this repo? This repo seems the best repo opensource out there
Just wanted to ask since I have spent a tremendous amount of time wasting on testdriving frontends for docker so far. Can this be used as is now to manage the basics of docker containers?

**Comment by kwk** [comment] 2015-07-23 11:27
@krunchyal Thank you for reporting your problem. I understand you must be frustrated.

I cannot confirm the problem with the most simplest of all settings, can you?

```
docker run -it --rm \
  -e ENV_DOCKER_REGISTRY_HOST=my-docker-host \
  -e ENV_DOCKER_REGISTRY_PORT=80 \
  -p 8081:80 \
  konradkleine/docker-registry-frontend
```

**Notice that I'm not running it in background with `-d` but in foreground using `-it`. Any output from you can help determine where the problem is.**

This is the expected output on my machine
```
Module auth_kerb disabled.
To activate the new configuration, you need to run:
  service apache2 restart
Module ssl already disabled
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
[ ok ] Stopping web server: apache2.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.208. Set the 'ServerName' directive globally to suppress this message
```

Can you please tell me what your configuration is? @moimael please also tell me your configuration.

I need to know how your registry is configured. On which port does your registry operate. Does it sit behind SSL or something or is authorization involved somehow? What is the exact command line or docker-compose setting you use to start your frontend?

Just to be correct, this is no frontend for Docker *containers* but rather for images and repos stored in a registry. And yes, this repo is usable to manage docker registry tasks like browsing, tagging and deletion of images and repositories.

And remember, this is an open source project so please feel free to help improve it in whatever way you think. **You're already helping a lot just by reporting your problems by the way!**

**Comment by moimael** [comment] 2015-07-23 11:34
It worked well before i pulled the last container revision. Container start without issues and nothing is wrong in the logs.

```
    - ENV_DOCKER_REGISTRY_SCHEME=https
    - ENV_DOCKER_REGISTRY_HOST=<domain_name>
    - ENV_DOCKER_REGISTRY_PORT=5000
    - ENV_DOCKER_REGISTRY_USE_SSL=1
```

registry frontend listen on port 80.
I can access the UI and the registry, but the UI can't access the registry. It tries to call http://<domain_name>/v1/?q= when it should try to call https://<domain_name>:5000/v1/?q=.

Env var are set in the container and in the apache env file but do not seems to be picked up by registry frontend.

**Comment by krunchyal** [comment] 2015-07-23 11:38
Ran the registry with:
`docker run -d --name registry-v1 \
    -p 5000:5000 \
    -e STORAGE_PATH=/opt/registry/storage \
    -v /var/lib/docker/storage/registry:/opt/registry/storage \
    registry:0.9.1`

Ran the frontend with:
`docker run -d --name registry-frontend \
    -e ENV_DOCKER_REGISTRY_HOST=192.168.x.x \
    -e ENV_DOCKER_REGISTRY_PORT=5000 \
    -p 80:80 \
    konradkleine/docker-registry-frontend`

**Comment by kwk** [comment] 2015-07-23 12:11
@krunchyal Thank you for your reply.

Please know, that the registry when hosted on `http://localhost:80/` always has called `http://localhost:80/v1/` and **not** `http://localhost:5000/v1`. This is to allow cross-origin requests. The work is done by the apache running on the frontend. It forwards/tunnels/proxies requests to `http://localhost:5000/v1`.

That said, I suggest you do the following and paste the outputs of each step here:

1. Run you registry-frontend as usual:
```
docker run -d --name registry-frontend \
    -e ENV_DOCKER_REGISTRY_HOST=192.168.x.x \
    -e ENV_DOCKER_REGISTRY_PORT=5000 \
    -p 80:80 \
    konradkleine/docker-registry-frontend
```
2. Get the apache's error log: `docker exec -it registry-frontend cat /var/log/apache2/error.log`
3. Get the apache's error log: `docker exec -it registry-frontend cat /var/log/apache2/access.log`
4. Get the apache config as it was written in the container `docker exec -it registry-frontend cat /etc/apache2/envvars`

**Comment by krunchyal** [comment] 2015-07-23 12:16
1. `docker exec -it registry-frontend cat /var/log/apache2/error.log
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message
[Thu Jul 23 12:13:15.226659 2015] [mpm_event:notice] [pid 38:tid 139975620769664] AH00489: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Thu Jul 23 12:13:15.227909 2015] [core:notice] [pid 38:tid 139975620769664] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'`

2. did not exist
3. `
docker exec -it registry-frontend cat /etc/apache2/envvars
# envvars - default environment variables for apache2ctl

# this won't be correct after changing uid
unset HOME

# for supporting multiple apache2 instances
if [ "${APACHE_CONFDIR##/etc/apache2-}" != "${APACHE_CONFDIR}" ] ; then
        SUFFIX="-${APACHE_CONFDIR##/etc/apache2-}"
else
        SUFFIX=
fi

# Since there is no sane way to get the parsed apache2 config in scripts, some
# settings are defined via environment variables and then used in apache2ctl,
# /etc/init.d/apache2, /etc/logrotate.d/apache2, etc.
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data
# temporary state file location. This might be changed to /run in Wheezy+1
export APACHE_PID_FILE=/var/run/apache2/apache2$SUFFIX.pid
export APACHE_RUN_DIR=/var/run/apache2$SUFFIX
export APACHE_LOCK_DIR=/var/lock/apache2$SUFFIX
# Only /var/log/apache2 is handled by /etc/logrotate.d/apache2.
export APACHE_LOG_DIR=/var/log/apache2$SUFFIX

## The locale used by some modules like mod_dav
export LANG=C
## Uncomment the following line to use the system default locale instead:
#. /etc/default/locale

export LANG

## The command to get the status for 'apache2ctl status'.
## Some packages providing 'www-browser' need '--dump' instead of '-dump'.
#export APACHE_LYNX='www-browser -dump'

## If you need a higher file descriptor limit, uncomment and adjust the
## following line (default is 8192):
#APACHE_ULIMIT_MAX_FILES='ulimit -n 65536'

## If you would like to pass arguments to the web server, add them below
## to the APACHE_ARGUMENTS environment.
#export APACHE_ARGUMENTS=''

## Enable the debug mode for maintainer scripts.
## This will produce a verbose output on package installations of web server modules and web application
## installations which interact with Apache
#export APACHE2_MAINTSCRIPT_DEBUG=1
export DOCKER_REGISTRY_HOST=192.168.x.x
export DOCKER_REGISTRY_PORT=5000
export REGISTRY_PROXY_FQDN=192.168.x.x
export REGISTRY_PROXY_PORT=5000
export DOCKER_REGISTRY_SCHEME=http
[root@iaas-a-reg02 ~]# ^C
[root@iaas-a-reg02 ~]# docker stop registry-frontend
registry-frontend
[root@iaas-a-reg02 ~]# docker rm registry-frontend
registry-frontend
[root@iaas-a-reg02 ~]# docker run -d --name registry-frontend     -e ENV_DOCKER_REGISTRY_HOST=10.240.64.217     -e ENV_DOCKER_REGISTRY_PORT=5000     -p 80:80     konradkleine/docker-registry-frontend
28e960bb5c64af5bc8c76cadb5e7c42a65754dcfbe3f2cf42da48698ef67f824
[root@iaas-a-reg02 ~]# docker exec -it registry-frontend cat /etc/apache2/envvars
# envvars - default environment variables for apache2ctl

# this won't be correct after changing uid
unset HOME

# for supporting multiple apache2 instances
if [ "${APACHE_CONFDIR##/etc/apache2-}" != "${APACHE_CONFDIR}" ] ; then
        SUFFIX="-${APACHE_CONFDIR##/etc/apache2-}"
else
        SUFFIX=
fi

# Since there is no sane way to get the parsed apache2 config in scripts, some
# settings are defined via environment variables and then used in apache2ctl,
# /etc/init.d/apache2, /etc/logrotate.d/apache2, etc.
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data
# temporary state file location. This might be changed to /run in Wheezy+1
export APACHE_PID_FILE=/var/run/apache2/apache2$SUFFIX.pid
export APACHE_RUN_DIR=/var/run/apache2$SUFFIX
export APACHE_LOCK_DIR=/var/lock/apache2$SUFFIX
# Only /var/log/apache2 is handled by /etc/logrotate.d/apache2.
export APACHE_LOG_DIR=/var/log/apache2$SUFFIX

## The locale used by some modules like mod_dav
export LANG=C
## Uncomment the following line to use the system default locale instead:
#. /etc/default/locale

export LANG

## The command to get the status for 'apache2ctl status'.
## Some packages providing 'www-browser' need '--dump' instead of '-dump'.
#export APACHE_LYNX='www-browser -dump'

## If you need a higher file descriptor limit, uncomment and adjust the
## following line (default is 8192):
#APACHE_ULIMIT_MAX_FILES='ulimit -n 65536'

## If you would like to pass arguments to the web server, add them below
## to the APACHE_ARGUMENTS environment.
#export APACHE_ARGUMENTS=''

## Enable the debug mode for maintainer scripts.
## This will produce a verbose output on package installations of web server modules and web application
## installations which interact with Apache
#export APACHE2_MAINTSCRIPT_DEBUG=1
export DOCKER_REGISTRY_HOST=10.240.64.217
export DOCKER_REGISTRY_PORT=5000
export REGISTRY_PROXY_FQDN=10.240.64.217
export REGISTRY_PROXY_PORT=5000
export DOCKER_REGISTRY_SCHEME=http
`

**Comment by kwk** [comment] 2015-07-23 12:40
@krunchyal I'm sorry but apparently you have to do something in the UI for an error to appear. Then repeat the steps please. Also, write down what you've done in the UI. Thank you in advance.

**Comment by krunchyal** [comment] 2015-07-23 12:43
Loaded the webUI, clicked browse repositories. Nothing ever shows...
1. `error.log`
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.7. Set the 'ServerName' directive globally to suppress this message
[Thu Jul 23 12:16:03.284213 2015] [mpm_event:notice] [pid 39:tid 140658245797760] AH00489: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Thu Jul 23 12:16:03.284408 2015] [core:notice] [pid 39:tid 140658245797760] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[Thu Jul 23 12:41:27.593507 2015] [proxy:error] [pid 40:tid 140657981101824] (113)No route to host: AH00957: HTTP: attempt to connect to 10.240.64.217:5000 (10.240.64.217) failed
[Thu Jul 23 12:41:27.593586 2015] [proxy:error] [pid 40:tid 140657981101824] AH00959: ap_proxy_connect_backend disabling worker for (10.240.64.217) for 60s
[Thu Jul 23 12:41:27.593601 2015] [proxy_http:error] [pid 40:tid 140657981101824] [client 10.240.24.45:53998] AH01114: HTTP: failed to make connection to backend: 10.240.64.217, referer: http://10.240.64.217/repositories
```
2. `access.log` still do not exist
3. `envvars` truncated based on your edit above...
```
export DOCKER_REGISTRY_HOST=10.240.64.217
export DOCKER_REGISTRY_PORT=5000
export REGISTRY_PROXY_FQDN=10.240.64.217
export REGISTRY_PROXY_PORT=5000
export DOCKER_REGISTRY_SCHEME=http
```

**Comment by kwk** [comment] 2015-07-23 12:49
When you have the frontend running, what is the output of this command?

```
docker exec -it --rm registry-frontend ping 10.240.64.217
```

If this outputs errors I suggest you go take a look at `/etc/default/docker` to configure routing and run `service docker restart` on the frontend host.

**Comment by krunchyal** [comment] 2015-07-23 13:00
```
docker exec -it registry-frontend ping 10.240.64.217
PING 10.240.64.217 (10.240.64.217): 56 data bytes
64 bytes from 10.240.64.217: icmp_seq=0 ttl=64 time=0.122 ms
64 bytes from 10.240.64.217: icmp_seq=1 ttl=64 time=0.086 ms
```

**Comment by kwk** [comment] 2015-07-23 13:15
Hm, and what is the output of `curl -v http://10.240.64.217:5000/v1/_ping` from your docker host?

**Comment by krunchyal** [comment] 2015-07-23 13:50
```
curl -v http://10.240.64.217:5000/v1/_ping
* About to connect() to 10.240.64.217 port 5000 (#0)
*   Trying 10.240.64.217...
* Connected to 10.240.64.217 (10.240.64.217) port 5000 (#0)
> GET /v1/_ping HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.240.64.217:5000
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: gunicorn/19.1.1
< Date: Thu, 23 Jul 2015 13:50:17 GMT
< Connection: keep-alive
< X-Docker-Registry-Config: dev
< Expires: -1
< X-Docker-Registry-Standalone: True
< Pragma: no-cache
< Cache-Control: no-cache
< Content-Type: application/json
< Content-Length: 1540
<
{"host": ["Linux", "0aee931742f3", "3.10.0-229.7.2.el7.x86_64", "#1 SMP Tue Jun 23 05:02:16 PDT 2015", "x86_64", "x86_64"], "launch": ["/usr/local/bin/gunicorn", "--access-logfile", "-", "--error-logfile", "-", "--max-requests", "100", "-k", "gevent", "--graceful-timeout", "3600", "-t", "3600", "-w", "4", "-b", "0.0.0.0:5000", "--reload", "docker_registry.wsgi:application"], "versions": {"M2Crypto.m2xmlrpclib": "0.22", "SocketServer": "0.4", "argparse": "1.1", "backports.lzma": "0.0.3", "blinker": "1.3", "cPickle": "1.71", "cgi": "2.6", "ctypes": "1.1.0", "decimal": "1.70", "distutils": "2.7.6", "docker_registry.app": "0.9.1", "docker_registry.core": "2.0.3", "docker_registry.server": "0.9.1", "email": "4.0.3", "flask": "0.10.1", "gevent": "1.0.1", "greenlet": "0.4.7", "gunicorn": "19.1.1", "gunicorn.arbiter": "19.1.1", "gunicorn.config": "19.1.1", "gunicorn.six": "1.2.0", "jinja2": "2.7.3", "json": "2.0.9", "logging": "0.5.1.2", "parser": "0.5", "pickle": "$Revision: 72223 $", "platform": "1.0.7", "pyexpat":* Connection #0 to host 10.240.64.217 left intact
 "2.7.6", "python": "2.7.6 (default, Mar 22 2014, 22:59:56) \n[GCC 4.8.2]", "re": "2.2.1", "redis": "2.10.3", "requests": "2.3.0", "requests.packages.chardet": "2.2.1", "requests.packages.urllib3": "dev", "requests.packages.urllib3.packages.six": "1.2.0", "requests.utils": "2.3.0", "simplejson": "3.6.2", "sqlalchemy": "0.9.4", "tarfile": "$Revision: 85213 $", "urllib": "1.17", "urllib2": "2.7", "werkzeug": "0.10.4", "xml.parsers.expat": "$Revision: 17640 $", "xmlrpclib": "1.0.1", "yaml": "3.11", "zlib": "1.0"}}
```

**Comment by kwk** [comment] 2015-07-23 13:57
Ok, now I'm officially out of ideas :(

**Comment by krunchyal** [comment] 2015-07-23 14:28
what changed between those two commits? i've replicated this on a couple of fresh VMs here...

**Comment by kwk** [comment] 2015-07-23 14:43
@krunchyal This is the only change I can imagine causing trouble: cb3c6505d7bc04e687d527250588592ae8071d48 . Try cloning my repo and building your own image without this change to see if it works:

```bash
$ git clone https://github.com/kwk/docker-registry-frontend.git
$ cd docker-registry-frontend
$ git revert -n cb3c6505d7bc04e687d527250588592ae8071d48
$ docker build -t krunchyal-frontend .
$ docker run -d --name registry-frontend \
    -e ENV_DOCKER_REGISTRY_HOST=192.168.x.x \
    -e ENV_DOCKER_REGISTRY_PORT=5000 \
    -p 80:80 \
    krunchyal-frontend 
```

Good luck.

**Comment by krunchyal** [comment] 2015-07-23 14:59
Same thing...

```
docker exec -it registry-frontend cat /var/log/apache2/error.log
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.14. Set the 'ServerName' directive globally to suppress this message
[Thu Jul 23 14:56:34.823955 2015] [mpm_event:notice] [pid 38:tid 140230105446272] AH00489: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Thu Jul 23 14:56:34.824624 2015] [core:notice] [pid 38:tid 140230105446272] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[Thu Jul 23 14:56:59.643504 2015] [proxy:error] [pid 39:tid 140229927229184] (113)No route to host: AH00957: HTTP: attempt to connect to 10.240.64.217:5000 (10.240.64.217) failed
[Thu Jul 23 14:56:59.643571 2015] [proxy:error] [pid 39:tid 140229927229184] AH00959: ap_proxy_connect_backend disabling worker for (10.240.64.217) for 60s
[Thu Jul 23 14:56:59.643586 2015] [proxy_http:error] [pid 39:tid 140229927229184] [client 10.240.24.45:55337] AH01114: HTTP: failed to make connection to backend: 10.240.64.217, referer: http://10.240.64.217/repositories
```
2. `envvars`
```
export DOCKER_REGISTRY_HOST=10.240.64.217
export DOCKER_REGISTRY_PORT=5000
export REGISTRY_PROXY_FQDN=10.240.64.217
export REGISTRY_PROXY_PORT=5000
export DOCKER_REGISTRY_SCHEME=http
```

**Comment by rubytastic** [comment] 2015-07-25 15:55
Im running OSX yosemite, it does not show any images or containers after the intro page button is clicked. Shall post back later here some more information

**Comment by rubytastic** [comment] 2015-07-25 20:09
<img width="1279" alt="screen shot 2015-07-25 at 22 07 45" src="https://cloud.githubusercontent.com/assets/189632/8891076/9a50b694-3319-11e5-9850-5cba7f98f2b1.png">

For me its just not loading the containers, also the removal button is listed 2 times.
The blue loading bar at the top just stays there at 99% and never completes.

I ran the frontend with 

 docker run   -d   -e ENV_DOCKER_REGISTRY_HOST=localhost   -e ENV_DOCKER_REGISTRY_PORT=5000   -p 8080:80   konradkleine/docker-registry-frontend

And the registry with the default command listed in the documentation

**Comment by krunchyal** [comment] 2015-07-25 20:47
This is the same as the issue I have worked through above.

**Comment by rubytastic** [comment] 2015-07-25 20:50
Correct just confirming the problem is the same and seems related to the codebase or the registry.

**Comment by 0x46616c6b** [comment] 2015-07-29 08:29
The Problem is that you forgot to activate the search backend of the registry. In default there is no search backend activated and so the /v1/search is disabled.

**Comment by kwk** [comment] 2015-07-29 08:37
@0x46616c6b Good point. @krunchyal How does your `config.yml` for the registry look like? Try finding a line that says `search_backend: _env:SEARCH_BACKEND:sqlalchemy` and copy it to whatever your environment is (`prod`, `test`, or `dev` maybe?). In the `test` environment of the the [sample `config.yml`](https://github.com/docker/docker-registry/blob/master/config/config_sample.yml#L214) there's a search backend configured.

**Comment by rubytastic** [comment] 2015-07-29 09:45
@kwk 
The config.yml you refer to where does that reside?
Be trying to activate the search backend and then repost results back here.

**Comment by rubytastic** [comment] 2015-07-29 10:12
I combined the registry startup params, and now using this:

REGISTRY:
docker run \
    -d --name registry-v1 \
    -e SETTINGS_FLAVOR=local \
    -e STORAGE_PATH=/registry \
    -e SEARCH_BACKEND=sqlalchemy \
    -e LOGLEVEL=DEBUG \
    -p 5000:5000 \
    registry:0.9.1

FRONTEND:
docker run \
  -d \
  -e ENV_DOCKER_REGISTRY_HOST=localhost \
  -e ENV_DOCKER_REGISTRY_PORT=80 \
  -p 8080:80 \
  konradkleine/docker-registry-frontend

docker ps:

CONTAINER ID        IMAGE                                   COMMAND                CREATED              STATUS              PORTS                                                NAMES
22d4a80851bd        konradkleine/docker-registry-frontend   "/bin/sh -c $START_S   About a minute ago   Up 54 seconds       443/tcp, 0.0.0.0:8080->80/tcp                        loving_lumiere      
ec227f63e277        registry:0.9.1                          "docker-registry"      About a minute ago   Up About a minute   0.0.0.0:5000->5000/tcp                               registry-v1       

Problem:
Connecting to localhost:80 fails and throws a not found error. 
Any thoughts?

**Comment by kwk** [comment] 2015-07-29 10:51
@rubytastic I'm sorry to say this but let's not escalate this issue into a support on docker commands, okay? Just search for "Bind failed: port is already allocated" and I'm sure you find the answer. In short: you seem to have a container (not necessarily running) that binds these port. I suggest you do `docker rm $(docker ps -qa)` to get a fresh start. 

The original problem doesn't seem to be related to the docker-registry-frontend but to the registry itself which didn't had a search backend configured.

I'll close this issue now.

**Closed by kwk** 2015-07-29 10:51 UTC
Labels: bug

**Comment by krunchyal** [comment] 2015-07-29 11:11
Still an issue for me with the following commands:
```
docker run -d --name registry-frontend     -e ENV_DOCKER_REGISTRY_HOST=10.240.64.217     -e ENV_DOCKER_REGISTRY_PORT=5000     -p 80:80     konradkleine/docker-registry-frontend
```

and

```
docker run -d --name registry-v1 \
   -p 5000:5000 \
   -e STORAGE_PATH=/opt/registry/storage \
   -e SETTINGS_FLAVOUR=local \
   -e SEARCH_BACKEND=sqlalchemy \
   -v /var/lib/docker/storage/registry:/opt/registry/storage\ 
   registry:0.9.1
```
```

**Comment by rubytastic** [comment] 2015-07-29 13:17
@krunchyal 
Great it brought you a step closer. I have still issue it not accepting localhost:80 which Ill be investigating outside this topic. What is your error problem at the moment?

@kwk 
No problem your right will investigate the port 80 not available, hope it will work then

**Comment by rubytastic** [comment] 2015-07-29 13:42
@krunchyal 
Great it brought you a step closer. I have still issue it not accepting localhost:80 which Ill be investigating outside this topic. What is your error problem at the moment?

@kwk 
No problem your right will investigate the port 80 not available, hope it will work then

**Comment by rubytastic** [comment] 2015-07-29 13:43
@kwk , @krunchyal 
It still fails, 
I pushed the redis container to the local repository without problems but the frontend is not picking it up even after restart. Also 2x the delete button is shown just like in my previous screenshot.
Don't think the issue is resolved and we should further investigate why this happens.

**Comment by kwk** [comment] 2015-07-29 13:56
@rubytastic @krunchyal The delete button showing twice is normal. If there were repos/images, the first one would be above, the second below the list of repos/images. Please, try to stick to the absolute minimum of setup; otherwise I cannot help you.

Why are you trying to get `http://docker:8080/scripts/directives/repository-list-directive.html`? This file does no longer exist once the frontend is packaged into a Docker image.

**Comment by rubytastic** [comment] 2015-07-29 15:07
@kwk
The frontend is calling this directives/repository-list...html file

**Comment by krunchyal** [comment] 2015-08-04 10:16
This is still an issue for me. I do not think it should be closed.

**Comment by rubytastic** [comment] 2015-08-04 20:06
You can use the awk repo instead which worked fine for me.

**Comment by krunchyal** [comment] 2015-08-04 20:09
Sorry, which?

On 4 August 2015 at 21:06, rubytastic <notifications@github.com> wrote:

> You can use the awk repo instead which worked fine for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kwk/docker-registry-frontend/issues/57#issuecomment-127741434>
> .
>



-- 
Alex Kretzschmar
07796 863 373

**Comment by turnerguo** [comment] 2017-01-04 12:29
I've tried v2, and the "503 Service Unavailable" issue always show me, is the final docker image correct on docker hub? I didn't tried the source build.
