### ISSUE TITLE
Untag - delete a image

### ISSUE THREAD

**Issue by sunshine69** [kwk/docker-registry-frontend#105] opened 2016-03-07 01:41 UTC
Hi,

The old version (v1) has a feature that allow to untag an image. And then there is a third party script which will find a hash that is not tagged anything and remove them from the file system.

I would like to have a feature like that to remove/cleanup old docker images hosted in the registry.

Thanks

**Comment by HadesArchitect** [comment] 2016-04-11 07:53
Really nice-to-have.

**Comment by distributorofpain** [comment] 2016-06-03 00:02
yes please.  :smile:

**Comment by marcelorodrigo** [comment] 2016-06-06 20:27
+1 for untag an image

**Comment by kwk** [comment] 2016-08-11 05:10
Duplicate of #106

**Closed as completed by kwk** 2016-08-11 05:10 UTC
