### ISSUE TITLE
can not display reposity

### ISSUE THREAD

**Issue by loveai88** [kwk/docker-registry-frontend#61] opened 2015-09-14 03:16 UTC
I run resiftry v2 like this 
```
docker run -d -p 5000:5000 --restart=always --name registry-v2 \
  -v ~/registry-v2:/var/lib/registry \
  registry:2
```

and run kwk like this 
```
  docker run \
    -d \
    -e ENV_DOCKER_REGISTRY_HOST=172.19.103.36 \
    -e ENV_DOCKER_REGISTRY_PORT=5000 \
    -p 80:80 \
    konradkleine/docker-registry-frontend:v2
```

I push a new image to v2,but I can not find it in kwk,why?

This is the log about kwk
```
Module auth_kerb disabled.
To activate the new configuration, you need to run:
  service apache2 restart
Module ssl already disabled
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
Stopping web server: apache2.
/usr/sbin/apache2ctl: 87: ulimit: error setting limit (Operation not permitted)
Setting ulimit failed. See README.Debian for more information.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.16. Set the 'ServerName' directive globally to suppress this message
```

Thanks

**Comment by kwk** [comment] 2015-09-14 06:53
This is a duplicate of #47 . Closing in favor of Issue #47.

**Closed by kwk** 2015-09-14 06:53 UTC
Labels: duplicate
